name: Fast CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'configs/**'
      - '*.json'
      - '*.js'
      - '*.ts'
      - '*.tsx'
      - '.github/workflows/ci-fast.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  TIMEOUT_MINUTES: 5

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit --progress=false
          npx playwright install chromium --with-deps

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            dist/
            .vite/
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Run fast test suite
        run: npm run test:ci
        timeout-minutes: 5
        env:
          CI: true
          NODE_ENV: test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fast-test-results
          path: |
            test-results/
            coverage/
          retention-days: 3

  fast-tests-summary:
    runs-on: ubuntu-latest
    needs: [fast-tests]
    if: always()
    
    steps:
      - name: Test Summary
        run: |
          echo "## Fast CI Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.fast-tests.result }}" = "success" ]; then
            echo "✅ **Fast tests passed** - Ready for merge" >> $GITHUB_STEP_SUMMARY
            echo "- Unit tests: ✅ Passed" >> $GITHUB_STEP_SUMMARY
            echo "- Type checking: ✅ Passed" >> $GITHUB_STEP_SUMMARY
            echo "- Linting: ✅ Passed" >> $GITHUB_STEP_SUMMARY
            echo "- Build verification: ✅ Passed" >> $GITHUB_STEP_SUMMARY
            echo "- Smoke tests: ✅ Passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Total runtime**: Under 5 minutes ⚡" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Fast tests failed** - Blocking merge" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please fix the failing tests before merging." >> $GITHUB_STEP_SUMMARY
            echo "Run \`npm run test:fast\` locally to reproduce." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "💡 **Optional**: Run comprehensive tests with \`gh workflow run tests-optional.yml\`" >> $GITHUB_STEP_SUMMARY

      - name: Report status
        if: failure()
        run: |
          echo "❌ Fast CI failed - blocking merge"
          exit 1