name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        
    name: Unit Tests (Node ${{ matrix.node-version }})
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check
        run: npm run type-check
        
      - name: Run unit tests
        run: npm run test:unit:coverage
        
      - name: Upload coverage to Codecov
        if: matrix.node-version == '20'
        uses: codecov/codecov-action@v4
        with:
          file: ./test-results/coverage/unit/lcov.info
          flags: unit-tests
          name: unit-tests-coverage
          fail_ci_if_error: false
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-node-${{ matrix.node-version }}
          path: |
            test-results/junit/unit-results.xml
            test-results/json/unit-results.json
            test-results/html/unit-report.html
            test-results/coverage/unit/
          retention-days: 30
          
      - name: Publish unit test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results (Node ${{ matrix.node-version }})
          path: test-results/junit/unit-results.xml
          reporter: java-junit
          fail-on-error: false
          
  unit-tests-summary:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: always()
    
    steps:
      - name: Unit Tests Summary
        run: |
          echo "### 🧪 Unit Tests Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Node Version | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| 18 | ${{ needs.unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 20 | ${{ needs.unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 **Coverage Report**: Available in artifacts" >> $GITHUB_STEP_SUMMARY
          echo "🎯 **Target Coverage**: 95% statements, 90% branches" >> $GITHUB_STEP_SUMMARY